### ISSUE TITLE
Modificaciones al script

### ISSUE THREAD

**Issue by JJ** [oslugr/ugrinvestiga#2]
1. Los menús en pantalla son **LA MUERTE**. Usa opciones de línea de órdenes. Aunque en este caso mejor simplemente produce el CSV y que se ordene con la hoja de cálculo
2. Pon el tiempo de espera configurable. Si no son muchos, se puede hacer del tirón. Incluso ponlo dependiendo del número de filas: si son más de 2500 es cuando tienes problemas
3. En Perl moderno no se debe usar $_. Eso ya lo modifico yo.

**Comment by germaaan** [comment]
He estado haciendo pruebas con el listado completo de investigadores y un tiempo de espera de 30 segundos entre consulta, la ejecución termina fallando con tiempo de espera de 30 segundos. Con 60 segundos espera, por ahora no ha fallado, pero no me ha dado tiempo a que termine de probarse el listado entero. Si esto no da problemas, pues ya intentaría establecer unos márgenes para calcular el tiempo de espera necesario.

**Comment by JJ** [comment]
Guay.

El 14 de abril de 2015, 8:39, German Martinez notifications@github.com
escribió:

> He estado haciendo pruebas con el listado completo de investigadores y un
> tiempo de espera de 30 segundos entre consulta, la ejecución termina
> fallando con tiempo de espera de 30 segundos. Con 60 segundos espera, por
> ahora no ha fallado, pero no me ha dado tiempo a que termine de probarse el
> listado entero. Si esto no da problemas, pues ya intentaría establecer unos
> márgenes para calcular el tiempo de espera necesario.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oslugr/ugrinvestiga/issues/2#issuecomment-92648636.

## 

JJ

**Comment by germaaan** [comment]
Solucionado con 7c0da5bfefa8669465e31152b43f604a86dadd1d.
