### ISSUE TITLE
Librería

### ISSUE THREAD

**Issue by JJ** [oslugr/ugrinvestiga#3]
En general, es una buena práctica hacerlo todo como librería: añadirle tests y demás. No sé si quizás merecería la pena añadir tu código a mi librería o crear una librería independiente...

**Comment by germaaan** [comment]
A mi se me hace algo con muy poca cosa lo que he hecho como para crear una librería independiente, sobretodo porque a grandes rasgos lo único que hace es utilizar tu librería y procesar la salida. Pero que vamos, si eso me pongo y lo hago así también.

**Comment by JJ** [comment]
Se podía crear aunque fuera un sólo módulo, más que nada por temas de
testeo e integración continua.

El 13 de abril de 2015, 21:57, German Martinez notifications@github.com
escribió:

> A mi se me hace algo con muy poca cosa lo que he hecho como para crear una
> librería independiente, sobretodo porque a grandes rasgos lo único que hace
> es utilizar tu librería y procesar la salida. Pero que vamos, si eso me
> pongo y lo hago así también.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oslugr/ugrinvestiga/issues/3#issuecomment-92479696.

## 

JJ

**Comment by germaaan** [comment]
Pues cuando termine con #2, me pongo con esto.
